#!/bin/bash/zsh
add_tag() {
    echo "$1" >> ~/.urgent-tags
}
remove_tag() {
    sed -i "/$1/d" ~/.urgent-tags
}

onclick() {
    leftwm-command "SendWorkspaceToTag $1 $2"
    remove_tag $3
}
onrightclick() {
    tag=$(($1 == 1 ? 0 : 1))
    leftwm-command "SendWorkspaceToTag $tag $2"
    remove_tag $3
}

if [[ "$1" == "-r" ]]; then
  echo $2 $3 $4
  onrightclick $2 $3 $4
  remove_tag $4
else
  onclick $1 $2 $3
  remove_tag $3
fi

