#!/bin/bash

LOCK_FILE="$HOME/.cache/eww-commands.lock"
EWW_BIN="/home/calvin/repos/eww/target/release/eww"
EWW_CONFIG="/home/calvin/repos/dotfiles/configs/eww"

calendar(){

run() {
    echo $1
    ${EWW_BIN} -c ${EWW_CONFIG} open "calendar$1"
}

# Run eww daemon if not running
if [[ ! `pidof eww` ]]; then
    ${EWW_BIN} -c ${EWW_CONFIG} daemon
    sleep 1
fi

# Open widgets
if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    run $1
else
    ${EWW_BIN} -c ${EWW_CONFIG} close "calendar$1"
    rm "$LOCK_FILE"
fi
}


commands(){

run() {
    echo $1
    ${EWW_BIN} -c ${EWW_CONFIG} open "commands$1"
}

# Run eww daemon if not running
if [[ ! `pidof eww` ]]; then
    ${EWW_BIN} -c ${EWW_CONFIG} daemon
    sleep 1
fi

# Open widgets
if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    run $1
else
    ${EWW_BIN} -c ${EWW_CONFIG} close "commands$1"
    rm "$LOCK_FILE"
fi
}



if [ "$1" = "launcher" ]; then
$HOME/.local/bin/launcher
elif [ "$1" = "wifi" ]; then
kitty -e nmtui
elif [ "$1" = "audio" ]; then
leftwm-command "ToggleScratchPad PavuControl"
elif [ "$1" = "calendar" ]; then
calendar $2
elif [ "$1" = "cmds" ]; then
commands $2
fi
