#!/bin/sh

symbol() {
[ $(nmcli | grep "^wlan0" | sed 's/\ connected\ to\ /Connected to /g' | cut -d ':' -f2) = disconnected ] && echo '' && exit
echo 
}

name() {
nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2
}

[ "$1" = "icon" ] && symbol && exit
[ "$1" = "name" ] && name && exit
